version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: docker-monitor-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dockermonitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: docker-monitor-backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:secret@postgres:5432/dockermonitor"
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  postgres_data:
